[package]
name = "jsonwith"
version = "0.0.12"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.5.10", features = ["derive", "cargo"] }

[lib]
name = "jsonwith"
path = "src/lib.rs"

[[bin]]
name = "jsonwith"
path = "src/bin/jsonwith.rs"
