[package]
name = "jsonwith"
version = "0.0.2"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.5", features = ["derive"] }

[lib]
name = "jsonwith"
path = "src/lib.rs"

[[bin]]
name = "jsonwith"
path = "src/bin/jsonwith.rs"
