[package]
name = "jsonwith"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }

# see https://stackoverflow.com/questions/26946646
[lib]
name = "jsonwith"
path = "src/lib.rs"

[[bin]]
name = "jsonwith"
path = "src/bin/jsonwith.rs"
