[package]
name = "jsonwith_formatter"
description = "work in progeress... "
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/enuesaa/jsonwith-formatter"

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }

[[bin]]
name = "jsonwith"
