[package]
name = "jsonwith"
version = "0.0.4"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.3.21", features = ["derive"] }

[lib]
name = "jsonwith"
path = "src/lib.rs"

[[bin]]
name = "jsonwith"
path = "src/bin/jsonwith.rs"
