[package]
name = "jsonwith_formatter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
wasm-bindgen = "0.2.83"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "json2yaml"
