name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.platform.target }}

      - run: mv target/${{ matrix.platform.target }}/release/jsonwith jsonwith-${TAG_NAME}-${{ matrix.platform.target }}

      - run: |
          cat <<'EOF' | envsubst > release.md
          # jsonwith ${TAG_NAME}
          ## Installation
          ```bash
          cargo install --git https://github.com/enuesaa/jsonwith --tag ${TAG_NAME}
          ```
          EOF

      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          body_path: release.md
          files: jsonwith-${TAG_NAME}-${{ matrix.platform.target }}
