name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test

      - if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - run: |
          echo "# jsonwith ${TAG_NAME}" > release.md;
          echo "## Installation" >> release.md;
          echo "~~~bash" >> release.md;
          echo "cargo install --git https://github.com/enuesaa/jsonwith --tag ${TAG_NAME}"  >> release.md;
          echo "~~~" >> release.md;

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          body_path: release.md
